development: &defaults
  database: swachh_bharat_development
  username: developer
  password: password
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5

test:
  database: swachh_bharat_test
  <<: *defaults

production:
  database: swachh_bharat_production
  <<: *defaults
